### ISSUE TITLE
still needed?

### ISSUE THREAD

**Issue by vaniron** [knightzmc/packet-limiter#4]
Have not found more info about this, is it still needed?

**Comment by BBaoVanC** [comment]
I think PaperMC/Paper#7368 obsoletes this

**Comment by bristermitten** [comment]
Yeah, I've no longer needed to use this (although my view distance and
things are still turned down)

**Comment by BBaoVanC** [comment]
Hmm one person on my server is still having issues even though that PR has been merged into Paper now. Is there something this plugin does that that PR doesn't do?

**Comment by BBaoVanC** [comment]
> Hmm one person on my server is still having issues even though that PR has been merged into Paper now. Is there something this plugin does that that PR doesn't do?

Nevermind, they're talking about some other kind of lag.
